name: kv test

on: [push, pull_request]

jobs:
  go-test-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Go test in Docker container
        run: make go-test-container